apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
              subPath: postgres
          env:
#            - name: PGPASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: k8s-test-project-secrets
#                  key: PGPASSWORD
            - name: POSTGRES_PASSWORD
#              value: 1q2w3e4r
              valueFrom:
                secretKeyRef:
                  name: k8s-test-project-secrets
                  key: PGPASSWORD
